insert into external_mock.shop (id, name)
values  (1, 'ALDI'),
        (2, 'LIDL'),
        (3, 'MORISSONS'),
        (4, 'POUNDLAND'),
        (5, 'SAINSBURY');

insert into external_mock.category (id, name)
values  (1, 'Carbonated Beverages'),
        (2, 'Milk'),
        (3, 'Fresh Bread & Rolls'),
        (11, 'Yogurt'),
        (12, 'Rfg Juices/Drinks'),
        (13, 'Ice Cream/Sherbet'),
        (14, 'Bottled Water'),
        (15, 'Soup'),
        (16, 'Crackers'),
        (17, 'Cookies'),
        (18, 'Bottled Juices'),
        (19, 'Coffee'),
        (20, 'Luncheon Meats'),
        (21, 'Breakfast Meats'),
        (22, 'Rfg Fresh Eggs'),
        (23, 'Toilet Tissue'),
        (24, 'Dog Food'),
        (25, 'Total Chocolate Candy'),
        (26, 'Fz Pizza'),
        (27, 'Rfg Salad/Coleslaw'),
        (28, 'Fz Novelties'),
        (29, 'Laundry Detergent'),
        (30, 'Vegetables'),
        (31, 'Fz Seafood'),
        (32, 'Spirits/Liquor'),
        (33, 'Snack Bars/Granola Bars'),
        (34, 'Baby Formula/Electrolytes'),
        (35, 'Processed Cheese'),
        (36, 'Shortening & Oil'),
        (37, 'Fz/Rfg Poultry'),
        (38, 'Cat Food'),
        (39, 'Spices/Seasonings'),
        (40, 'Dinner Sausage'),
        (41, 'Paper Towels'),
        (42, 'Fz Plain Vegetables'),
        (43, 'Creams/Creamers'),
        (44, 'Processed Fz/Rfg Poultry'),
        (45, 'Frankfurters'),
        (46, 'Pastry/Doughnuts'),
        (47, 'Sports Drinks'),
        (48, 'Fz Breakfast Food'),
        (49, 'Pasta'),
        (50, 'Spaghetti/Italian Sauce'),
        (51, 'Pickles/Relish/Olives'),
        (52, 'Mexican Foods'),
        (53, 'Canned/Bottled Fruit'),
        (54, 'Snack Nuts/Seeds/Corn Nuts'),
        (55, 'Seafood – Ss'),
        (56, 'Food & Trash Bags'),
        (57, 'Salad Dressings – Ss'),
        (58, 'Rfg Side Dishes'),
        (59, 'Rice'),
        (60, 'Total Non-Chocolate Candy'),
        (61, 'Butter'),
        (62, 'Dry Packaged Dinners'),
        (63, 'Fz Meat'),
        (64, 'Margarine/Spreads/Butter Blen'),
        (65, 'Dough/Biscuit Dough – Rfg'),
        (66, 'Tea/Coffee Ready-To-Drink'),
        (67, 'Mayonnaise'),
        (68, 'Baking Needs'),
        (69, 'Sugar'),
        (70, 'Ss Dinners'),
        (71, 'Cups & Plates'),
        (72, 'Baking Mixes'),
        (73, 'Tomato Products'),
        (74, 'Vitamins'),
        (75, 'Fz Potatoes/Onions'),
        (76, 'Rfg Meat'),
        (77, 'Soap'),
        (78, 'Bakery Snacks'),
        (79, 'Diapers'),
        (80, 'Household Cleaner'),
        (81, 'Pies & Cakes'),
        (82, 'Mexican Sauce'),
        (83, 'Ss Meat & Rfg Ham'),
        (84, 'Fz Appetizers/Snack Rolls'),
        (85, 'Dish Detergent'),
        (86, 'Cream Cheese/Cr Chs Spread'),
        (87, 'Peanut Butter'),
        (88, 'Jellies/Jams/Honey'),
        (89, 'Internal Analgesics'),
        (90, 'Gravy/Sauce Mixes'),
        (91, 'Cottage Cheese'),
        (92, 'Energy Drinks'),
        (93, 'Aseptic Juices'),
        (94, 'Gum'),
        (95, 'Rfg Entrees'),
        (96, 'Hot Cereal'),
        (97, 'Lunches – Rfg'),
        (98, 'Sour Cream'),
        (99, 'Mustard & Ketchup'),
        (100, 'All Other Sauces'),
        (101, 'Baby Food'),
        (102, 'Cold/Allergy/Sinus Tablets'),
        (103, 'Toothpaste'),
        (104, 'Tea – Bags/Loose'),
        (105, 'Weight Con/Nutrition Liq/Pwd'),
        (106, 'Fz Bread/Fz Dough'),
        (107, 'Pet Supplies'),
        (108, 'Gastrointestinal – Tablets'),
        (109, 'Facial Tissue'),
        (110, 'Sanitary Napkins/Tampons'),
        (111, 'Flour/Meal'),
        (112, 'Cat/Dog Litter'),
        (113, 'Dried Fruit'),
        (114, 'Shampoo'),
        (115, 'Popcorn/Popcorn Oil'),
        (116, 'Syrup/Molasses'),
        (117, 'Deodorant'),
        (118, 'Drink Mixes'),
        (119, 'Baking Nuts'),
        (120, 'Batteries'),
        (121, 'Air Fresheners'),
        (122, 'Gelatin/Pudding Prd And Mixes'),
        (123, 'Foils & Wraps'),
        (124, 'Desserts -Rfg'),
        (125, 'Baked Beans/Canned Bread'),
        (126, 'Fz Desserts/Topping'),
        (127, 'Skin Care'),
        (128, 'Blades'),
        (129, 'English Muffins'),
        (130, 'Spreads – Rfg'),
        (131, 'Rfg Whipped Toppings'),
        (132, 'Canned Juices – Ss'),
        (133, 'Rfg Dips'),
        (134, 'Fz Pies'),
        (135, 'Cleaning Tools/Mops/Brooms'),
        (136, 'Toaster Pastries/Tarts'),
        (137, 'Dry Fruit Snacks'),
        (138, 'Toothbrush/Dental Accesories'),
        (139, 'Barbeque Sauce'),
        (140, 'Rfg Teas/Coffee'),
        (141, 'Charcoal'),
        (142, 'Sugar Substitutes'),
        (7, 'Wine'),
        (143, 'Fz Fruit'),
        (144, 'Asian Food'),
        (145, 'Paper Napkins'),
        (146, 'Fabric Softener Liquid'),
        (147, 'Hair Conditioner'),
        (148, 'Seafood – Rfg'),
        (149, 'Moist Towelettes'),
        (150, 'Juices – Frozen'),
        (151, 'Dip/Dip Mixes – Ss\Candles'),
        (152, 'Dry Beans/Vegetables'),
        (153, 'Mouthwash'),
        (154, 'Misc. Snacks'),
        (155, 'Instant Potatoes'),
        (156, 'Coffee Creamer'),
        (157, 'Kitchen Storage'),
        (158, 'Vinegar'),
        (159, 'Eye/Contact Lens Care Product'),
        (160, 'Evaporated/Condensed Milk'),
        (161, 'Milk Flavoring/Cocoa Mixes'),
        (162, 'Frosting'),
        (163, 'Fz Prepared Vegetables'),
        (164, 'Hand & Body Lotion'),
        (165, 'Hair Coloring'),
        (166, 'Bleach'),
        (167, 'Breadcrumbs/Batters'),
        (168, 'Other Rfg Products'),
        (169, 'Non-Fruit Drinks'),
        (170, 'Light Bulbs'),
        (171, 'Fz Pasta'),
        (172, 'Laundry Care'),
        (173, 'Salad Toppings'),
        (174, 'Smokeless Tobacco'),
        (175, 'Fz Pot Pies'),
        (176, 'Dessert Toppings'),
        (177, 'Foil Pans'),
        (178, 'Pest Control'),
        (179, 'Tea – Instant Tea Mixes'),
        (180, 'Baked Goods – Rfg'),
        (181, 'Salad Dressing – Rfg'),
        (182, 'Misc Health Remedies'),
        (183, 'Adult Incontinence'),
        (184, 'Rfg Tortlla/Eggrll/Wontn Wrap'),
        (185, 'Dried Meat Snacks'),
        (186, 'Sponges & Scouring Pads'),
        (187, 'Pizza – Rfg'),
        (188, 'Steak/Worcestershire Sauce'),
        (189, 'Rug/Upholstery/Fabric Treatmt'),
        (190, 'Pancake Mixes'),
        (191, 'Pasta – Rfg'),
        (192, 'Fz Side Dishes'),
        (193, 'Stuffing Mixes'),
        (194, 'First Aid Treatment'),
        (195, 'First Aid Accessories'),
        (196, 'Premixed Cocktails/Coolers'),
        (197, 'Fabric Softener Sheets'),
        (198, 'Gastrointestinal – Liquid'),
        (199, 'Hair Styling Gel/Mousse'),
        (200, 'Cold/Allergy/Sinus Liquids'),
        (201, 'Cosmetics – Eye'),
        (202, 'Suntan Products'),
        (203, 'Firelog/Firestarter/Firewood'),
        (204, 'Pickles/Relish – Rfg'),
        (205, 'Disposable Tableware'),
        (206, 'Rice/Popcorn Cakes'),
        (207, 'Croutons'),
        (208, 'Hair Spray/Spritz'),
        (209, 'Household Cleaner Cloths'),
        (210, 'Cocktail Mixes'),
        (211, 'Cough Drops'),
        (212, 'Cosmetics – Facial'),
        (213, 'Baby Accessories'),
        (214, 'Nasal Products'),
        (215, 'Baby Needs'),
        (216, 'Hair Accessories'),
        (217, 'Marshmallows'),
        (218, 'Foot Care Products'),
        (219, 'Office Products'),
        (220, 'Coffee Filters'),
        (221, 'Cigars'),
        (222, 'Cosmetics – Nail'),
        (223, 'Cheesecakes'),
        (224, 'Feminine Needs'),
        (225, 'Specialty Nut Butter'),
        (226, 'Cough Syrup'),
        (227, 'Shaving Cream'),
        (228, 'Fz Corn On The Cob'),
        (229, 'Denture Products'),
        (230, 'Cotton Balls/Swabs'),
        (231, 'All Other Breakfast Food'),
        (232, 'Pizza Products'),
        (233, 'Socks'),
        (234, 'Shaving Lotion/Mens Fragrance'),
        (235, 'Ice Cream Cones/Mixes'),
        (236, 'Razors'),
        (237, 'Childrens Art Supplies'),
        (238, 'Cosmetics – Lip'),
        (239, 'Lighters'),
        (240, 'Furniture Polish'),
        (241, 'Water Softeners/Treatment'),
        (242, 'Other Frozen Foods'),
        (243, 'Writing Instruments'),
        (244, 'Automobile Fluids/Antifreeze'),
        (245, 'Contraceptives'),
        (246, 'External Analgesic Rubs'),
        (247, 'Gloves'),
        (248, 'Charcoal Lighter Fluids'),
        (249, 'Floor Cleaners/Wax Removers'),
        (250, 'Anti-Smoking Products'),
        (251, 'Sleeping Remedies'),
        (252, 'Water Filters/Devices'),
        (253, 'All Other Tobacco Products'),
        (254, 'Motor Oil'),
        (255, 'Family Planning'),
        (256, 'Pantyhose/Nylons'),
        (257, 'Fragrances – Women’s'),
        (258, 'Baking Cups/Paper'),
        (4, 'Salty Snacks'),
        (6, 'Natural Cheese'),
        (9, 'Cold Cereal'),
        (8, 'Fz Dinners/Entrees'),
        (10, 'Cigarettes'),
        (5, 'Beer/Ale/Alcoholic Cider');